version: '1'
services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  superset:
    image: superset_local:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - redis
    environment:
      SUPERSET_SECRET_KEY: 'ThisIsAsecretKey'
      SQLALCHEMY_DATABASE_URI: 'postgresql+psycopg2://superset:superset@db:5432/superset'
    # environment:
    #   MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    ports:
      - "8088:8088"
    volumes:
      - ./superset/superset_config.py:/etc/superset/superset_config.py
      - ./superset/superset_uploads:/app/superset_uploads
  
volumes:
  postgres:
  redis:
